from dotenv import load_dotenv
import os
from openai import OpenAI
import pandas as pd
import json


load_dotenv()

client = OpenAI(base_url="http://localhost:11434/v1", api_key="ollama")



with open("motor_insurance_metric_library.json", "r") as f:
    metric_library = json.load(f)

approved_metrics = [
    m for m in metric_library["metrics"] if m["status"] == "approved"
]

metric_lookup = {
    m["name"]: m["dax"] for m in approved_metrics
}
print(metric_lookup)



df = pd.read_csv("motor_insurance_claims.csv")

columns = list(df.columns)

print("Columns detected:", columns)


user_prompt = """
Metrics:
- Loss Ratio
- Total Claims
- Avg Claim Cost = AVERAGE(claim_amount)

Breakdown:
- state
- claim_date

Visuals:
- KPI
- trend
"""
system_prompt = f"""
You are a dashboard analysis agent for motor insurance data.

You have access to these approved metrics:
{json.dumps(metric_lookup, indent=2)}

You have access to these data columns:
{columns}

The user will ask for a dashboard. You must respond in JSON format like this:
{{
  "metrics": ["metric1", "metric2"],
  "breakdowns": ["column1", "column2"],
  "visuals": ["KPI", "trend"]
}}

Only use metrics from the approved list. Only use columns from the data.
"""

response = client.chat.completions.create(
    model="mistral",
    messages=[
        {"role": "system", "content": system_prompt},
        {"role": "user", "content": user_prompt}
    ]
)

agent_output = response.choices[0].message.content
print("Agent response:", agent_output)
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots

import re

# Extract JSON from Mistral's response
json_match = re.search(r'\{.*?\}', agent_output, re.DOTALL)
if json_match:
    plan = json.loads(json_match.group())
else:
    plan = {
        "metrics": ["Total Claims", "Average Claim Cost", "Loss Ratio"],
        "breakdowns": ["state", "claim_date"],
        "visuals": ["KPI", "trend"]
    }

print("Dashboard plan:", plan)

# Calculate the metrics from the data
figures = []

# KPI cards - always calculate all three regardless of Mistral's wording
loss_ratio = round(df["claim_amount"].sum() / df["premium"].sum(), 4)
fig1 = go.Figure(go.Indicator(mode="number", value=loss_ratio, title={"text": "Loss Ratio"}))
figures.append(fig1)

total_claims = df["claim_amount"].sum()
fig2 = go.Figure(go.Indicator(mode="number", value=total_claims, title={"text": "Total Claims"}))
figures.append(fig2)

avg_cost = round(df["claim_amount"].mean(), 2)
fig3 = go.Figure(go.Indicator(mode="number", value=avg_cost, title={"text": "Average Claim Cost"}))
figures.append(fig3)

# Trend chart by state
if "state" in plan.get("breakdowns", []):
    state_df = df.groupby("state")["claim_amount"].sum().reset_index()
    fig = px.bar(state_df, x="state", y="claim_amount", title="Total Claims by State")
    figures.append(fig)

# Trend chart by date
if "claim_date" in plan.get("breakdowns", []):
    df["claim_date"] = pd.to_datetime(df["claim_date"], dayfirst=True)
    date_df = df.groupby("claim_date")["claim_amount"].sum().reset_index()
    fig = px.line(date_df, x="claim_date", y="claim_amount", title="Claims Trend Over Time")
    figures.append(fig)

# Build professional HTML dashboard
import webbrowser

html_parts = []
for fig in figures:
    html_parts.append(fig.to_html(full_html=False, include_plotlyjs='cdn'))

# Separate KPI cards from charts
kpi_html = "".join([f'<div class="kpi-card">{p}</div>' for p in html_parts[:3]])
chart_html = "".join([f'<div class="chart-card">{p}</div>' for p in html_parts[3:]])

final_html = f"""
<!DOCTYPE html>
<html>
<head>
    <title>Motor Insurance Claims Dashboard</title>
    <style>
        * {{ margin: 0; padding: 0; box-sizing: border-box; }}
        body {{ font-family: 'Segoe UI', Arial, sans-serif; background: #f0f2f5; padding: 24px; }}
        .header {{ background: #1F3A6E; color: white; padding: 24px 32px; border-radius: 12px; margin-bottom: 24px; }}
        .header h1 {{ font-size: 24px; font-weight: 600; }}
        .header p {{ font-size: 13px; opacity: 0.75; margin-top: 4px; }}
        .kpi-row {{ display: flex; gap: 16px; margin-bottom: 24px; }}
        .kpi-card {{ flex: 1; background: white; border-radius: 12px; padding: 20px; box-shadow: 0 2px 8px rgba(0,0,0,0.07); }}
        .chart-card {{ background: white; border-radius: 12px; padding: 20px; margin-bottom: 24px; box-shadow: 0 2px 8px rgba(0,0,0,0.07); }}
        .footer {{ text-align: center; font-size: 12px; color: #999; margin-top: 8px; }}
    </style>
</head>
<body>
    <div class="header">
        <h1>Motor Insurance Claims Dashboard</h1>
        <p>Powered by Mistral AI running locally via Ollama</p>
    </div>
    <div class="kpi-row">
        {kpi_html}
    </div>
    {chart_html}
    <div class="footer">Generated by agent-driven-dashboard | Data processed locally | No data sent to cloud</div>
</body>
</html>
"""

with open("dashboard.html", "w") as f:
    f.write(final_html)

print("Dashboard saved as dashboard.html")
webbrowser.open("dashboard.html")
print("Opening dashboard in browser...")